services:
  db:
    image: postgres:latest
    container_name: postgres-ecommerce
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      PGDATA: data/postgres
    volumes:
      - db:/data/postgres
    networks:
      - api

volumes:
  db:

networks:
  api:
    driver: bridge

